frameworkVersion: '3'
service: aws-lambda-app-slack
provider:
  name: aws
  runtime: python3.10
  region: ap-northeast-1
  profile: data-root-user
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
            - lambda:InvokeAsync
          Resource: "*"
  environment:
    SERVERLESS_STAGE: ${opt:stage, 'prod'}
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_CLIENT_ID: ${env:SLACK_CLIENT_ID}
    SLACK_CLIENT_SECRET: ${env:SLACK_CLIENT_SECRET}
functions:
  app:
    handler: app_prod.handler
    events:
      - httpApi:
          path: /slack/events
          method: post
      - httpApi:
          path: /slack/install
          method: get
      - httpApi:
          path: /slack/oauth_redirect
          method: get

package:
  exclude:
    - "!.venv/**"
    - "!node_modules/**"
    - "!.idea/**"

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    zip: true
    slim: true
    # dockerizePip: true  # This option must be enabled for including Linux compatible *.so files
